Questo e`il messaggio di iscrizione a OnionMail.

Il tuo indirizzo mail su Tor e`:
%%MAIL%%

Sul client di posta dovrai collegarti tramite Tor
al server:
%%SERVER%%

I parametri sono:

SMTP Server: %%SERVER%%
User name: %%USER%%
Password: %%SMTPPASSWD%%

POP3 Server: %%SERVER%%
User name: %%USER%%
Password: %%POP3PASSWD%%

I messaggi possono essere lunghi fino a %%MSGSIZE%% byte.
Nella tua inbox ci possono essere fino a %%MAXMSG%% messaggi.
I messaggi saranno cancellati entro %%MSGOLD%% giorni.

Il nodo di uscita di default e`: "%%INET%%"

Per saperne di piu`, manda una mail con subject RULEZ a
server@%%QFDN%%

Ricordati di cancellare questo messaggio dopo aver messo
i dati al sicuro.

Queste sono le informazioni sul certificato SSL del server:
